[project]
name = "elon-ai"
version = "0.1.0"
description = "Simple LangChain Tryout!"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "isort>=6.0.1",
    "langchain>=0.3.27",
    "langchain-openai>=0.3.32",
    "python-dotenv>=1.1.1",
]
